name: "Get new brands"

on:
  workflow_dispatch:
  schedule:
    - cron: '03 02 * * 0'

jobs:
  find_new_brands:
    name: "Find new brands"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4

      - name: "Setup python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r ${GITHUB_WORKSPACE}/requirements.txt
        shell: bash

      - name: Setup jq
        run: sudo apt-get install jq

      - name: "Search brands"
        run: |
          echo "BRANDS<<EOF" >> $GITHUB_ENV
          echo $(python ${GITHUB_WORKSPACE}/get_brands.py) >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: "Extract brand IDs"
        run: |
          BRAND_IDS=$(echo $BRANDS | jq -r 'keys | join(", ")')
          echo "BRAND_IDS=$BRAND_IDS" >> $GITHUB_ENV

      - name: "Print brands"
        run: |
          cat ${GITHUB_WORKSPACE}/src/brands.json

      - name: Generate Markdown from JSON
        id: generate-markdown
        run: |
          echo "### Brands found: ${{ env.BRAND_IDS }}" > brands.md
          echo "" >> brands.md
          jq -r 'to_entries[] | "#### Brand ID: \(.key)\n" + (.value | to_entries[] | "- **\(.key):** \(.value)\n") + "\n"' src/brands.json >> brands.md
          echo "BRANDS_MARKDOWN<<EOF" >> $GITHUB_ENV
          cat brands.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: "Release"
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: src/brands.json
          branch: newBrand
          delete-branch: true
          title: "Update brand list"
          body: |
            ${{ env.BRANDS_MARKDOWN }}
          commit-message: "Auto add brand workflow"

  update_existing_brands:
    name: "Update existing brands"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4

      - name: Setup php and jq
        run: sudo apt-get install jq php php-cli

      - name: "Update brands file"
        run: |
          ./update_brands_from_stores.sh -d

      - name: "Print brands"
        run: cat ${GITHUB_WORKSPACE}/src/brands_infos.json

      - name: "Update Capabilities.php"
        id: update_php
        run: |
          PHP_UPDATES=$(php ./check_versions.php --appstore 2>&1)
          echo "$PHP_UPDATES"
          echo "PHP_UPDATES<<EOF" >> $GITHUB_ENV
          echo "$PHP_UPDATES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: "Validate PHP syntax"
        run: php -l src/Capabilities.php

      - name: "Release"
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            src/brands_infos.json
            src/Capabilities.php
          branch: brandFromStores
          delete-branch: true
          title: "Update brands infos from stores and modify php file"
          body: |
            ## Mises à jour des versions d'applications

            ${{ env.PHP_UPDATES }}
          commit-message: "Auto update brands from stores"
