name: Get new brands

on:
  workflow_dispatch
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Search brands
        run: | 
          echo "BRANDS=$(${GITHUB_WORKSPACE}/meari.brand_search.sh)" >> $GITHUB_ENV
          echo "${BRANDS}" > ${GITHUB_WORKSPACE}/src/new_brands.json

      - name: Print brands
        run: | 
          cat ${GITHUB_WORKSPACE}/src/new_brands.json

      - uses: peter-evans/create-pull-request@v6
        with:
          add-paths: src/new_brands.json
          branch: newBrand
          delete-branch: true
          title: "Update brand list"
          body: "New brand added: ${{ env.BRANDS }}"
          commit-message: "Auto add brand workflow"
