name: "Get new brands"

on:
  workflow_dispatch:
  schedule:
    - cron: 12 05 * * 1

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Checkout files"
        uses: actions/checkout@v3

      - name: "Setup python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r ${GITHUB_WORKSPACE}/requirements.txt
        shell: bash

      - name: Setup jq
        run: sudo apt-get install jq

      - name: "Search brands"
        run: |
          echo "BRANDS<<EOF" >> $GITHUB_ENV
          echo $(python ${GITHUB_WORKSPACE}/get_brands.py) >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: "Extract brand IDs"
        run: |
          BRAND_IDS=$(echo $BRANDS | jq -r 'keys | join(", ")')
          echo "BRAND_IDS=$BRAND_IDS" >> $GITHUB_ENV

      - name: "Print brands"
        run: |
          cat ${GITHUB_WORKSPACE}/src/brands.json

      - name: Generate Markdown from JSON
        id: generate-markdown
        run: |
          echo "### Brands found: ${{ env.BRANDS_IDS }}\n\n" > brands.md
          jq -r 'to_entries[] | "#### Brand ID: \(.key)\n" + (.value | to_entries[] | "- **\(.key):** \(.value)\n") + "\n"' src/brands.json >> brands.md
          echo "BRANDS_MARKDOWN<<EOF" >> $GITHUB_ENV
          echo $(cat brands.md) >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: peter-evans/create-pull-request@v6
        with:
          add-paths: src/brands.json
          branch: newBrand
          delete-branch: true
          title: "Update brand list"
          body: |
            ${{ env.BRANDS_MARKDOWN }}
          commit-message: "Auto add brand workflow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
