name: Get brands

on:
  workflow_dispatch
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - run: ${GITHUB_WORKSPACE}/meari.brand_search.sh          

      - uses: peter-evans/create-pull-request@v6
        with:
          path: 'src'
          branch: newBrand
          delete-branch: true
          title: "Update brand list"
          body: "New brand added"
          commit-message: "Auto add brand workflow"
