name: "Get new brands"

on:
  workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Checkout files"
         uses: actions/checkout@v3

      - name: "Setup python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r ${GITHUB_WORKSPACE}/requirements.txt
        shell: bash

      - name: "Search brands"
        run: |
          echo "BRANDS=$(${GITHUB_WORKSPACE}/get_brands.sh)" >> $GITHUB_ENV

      - name: "Extract brand IDs"
        run: |
          BRAND_IDS=$(echo $BRANDS | jq -r 'keys | join(", ")')
          echo "BRAND_IDS=$BRAND_IDS" >> $GITHUB_ENV

      - name: "Print brands"
        run: |
          cat ${GITHUB_WORKSPACE}/src/new_brands.json

      - uses: peter-evans/create-pull-request@v6
        with:
          add-paths: src/new_brands.json
          branch: newBrand
          delete-branch: true
          title: "Update brand list with IDs: ${{ env.BRAND_IDS }}"
          body: "New brands added: ${{ env.BRANDS }}"
          commit-message: "Auto add brand workflow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
