name: Get brands

on:
  workflow_dispatch
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Get brands now..."
        run: ${GITHUB_ACTION_PATH}/meari.brand_search.sh
        shell: sh

      - name: "Create Pull Request to plugin..."
        uses: peter-evans/create-pull-request@v6
        with:
          path: 'plugin'
          branch: newBrand
          delete-branch: true
          title: "Update brand list"
          body: "New brand added"
          commit-message: "Auto add brand workflow"
