name: Get brands

on:
  workflow_dispatch
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Get brands now..."
        shell: bash
        run: |
          echo ${{ github.action_path }}
          bash ${{ github.action_path }}/meari.brand_search.sh
    
      - name: "Create Pull Request to plugin..."
        uses: peter-evans/create-pull-request@v6
        with:
          path: 'plugin'
          branch: newBrand
          delete-branch: true
          title: "Update brand list"
          body: "New brand added"
          commit-message: "Auto add brand workflow"
